name: Terraform Apply

on:
  push:
    branches: ["main"]
    paths:
      - "infra/**"
      - ".github/workflows/**"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  apply:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write

    env:
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.5"

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init -input=false -reconfigure

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false tfplan